# stats available at
# https://travis-ci.org/strukturag/vlc-libde265/
language: c
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:strukturag/libde265
  - sudo apt-get update -qq
  - sudo apt-get install -y libde265-dev libvlccore-dev libmatroska-dev libebml-dev libdvbpsi-dev

script:
  - ./autogen.sh
  - ./configure
  - make
